---
apiVersion: batch/v1
kind: Job
metadata:
  name: testJob
spec:
  template:
    metadata:
      name: testJob
    spec:
      containers:
      - name: testJob
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never